update dynamic iframe to pass query string args
vtex-apps/iframe pull request #9
Opened 2020-03-27 17:37 UTC by mvandeusen

pass query string arguments to iframe url if present in page url

#### What problem is this solving?

allow query string arguments to passed down to iframe URLs so that query arg based filtering and tracking will function.

#### How should this be manually tested?

all stores in iframe:
https://iframeupdate--eriksbikeshop.myvtex.com/stores

args passed to iframe, which filters map and stores list to specified type and zip code:
https://iframeupdate--eriksbikeshop.myvtex.com/stores?type=Bike%20Rental&z=14502

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [ ] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements 

#### Notes

2020-03-27 19:40 UTC, polishq requested changes

2020-03-27 19:40 UTC, polishq commented on react/DynamicIframe.tsx
> +  const { query } = useRuntime()
You can combine this with the previous `useRuntime()` call like so:

`const {
  route: { params },
  query
} = useRuntime()`

2020-03-27 19:40 UTC, polishq commented on react/package.json
> +    "query-string": "^6.11.1",
You can remove `query-string` since you're not using it, that'll keep the package size down.

2020-03-27 20:18 UTC, klzns approved these changes

2020-03-30 17:19 UTC, polishq approved these changes

2020-03-30 17:20 UTC, merged